### ISSUE TITLE
Save button spinner doesn't stop in IE11

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-fileeditor#16]
Bizarre issue in IE11. When I clicked save, the glyphicon kept spinning for a time.

The `.spin` class is removed with jQuery, but for some reason IE didn't respect the style.

This behavior stopped when I opened up dev tools and I haven't been able to replicate it.

![spinningsave](https://cloud.githubusercontent.com/assets/2374718/15756247/641bbf46-28ce-11e6-9f36-c9b26c17c64f.png)

**Comment by brianmcmichael** [comment]
Some solutions discussed here. The "stop-spin" css option looks promising.
https://github.com/FortAwesome/Font-Awesome/issues/7572

**Comment by brianmcmichael** [comment]
This issue is still present in production May 2017.

**Comment by nickjer** [comment]
You could also test the last solution in that issue by adding the below to your `application.scss` file:

```scss
.fa {
    &:not(.fa-spin) {
        animation: none;
   }
}
```

and checking it in IE. This would require no added JS code on your part.

**Comment by MorganRodgers** [comment]
Won't fix
