### ISSUE TITLE
Horizontal scroll bar lost when word wrap turned off

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-fileeditor#22]
In the File Editor, the horizontal scroll bar can be lost even when word wrap is turned off and the text goes past the page. The only way to recover the scroll bar is to select a character after the frame cut off.
To reproduce: Create a new file, edit it, then type one long continuous word that extends past the frame. Then turn on then off Word Wrap. The horizontal scroll bar will then be gone. This can also be repeated after fixing the horizontal scroll bar.

https://github.com/OSC/ondemand-testing/issues/10#issuecomment-223632290

**Comment by ericfranz** [comment]
Seems like there is a fix for this available in the conversation on the issue you mentioned.

**Comment by brianmcmichael** [comment]
I have attempted that fix and it did not resolve this particular issue.

**Comment by brianmcmichael** [comment]
Another user reports similar behavior at https://github.com/ajaxorg/ace/issues/2336

Will continue tracking.

**Comment by brianmcmichael** [comment]
Updating to the latest Ace fixes the scroll bar disappearing.

See https://github.com/OSC/ood-fileeditor/pull/67
