### ISSUE TITLE
Don't stage .env.production

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-fileeditor#35]
You should not stage `.env.production` unless you made it generic enough to work on all portals. Maybe version some examples like `.env.production.osc` with documentation.

For instance, in the case of the AweSim deployment I had to modify `OOD_DATAROOT` and `OOD_DASHBOARD_TITLE`. If these variables are not necessary then feel free to remove them.

**Comment by brianmcmichael** [comment]
Done at https://github.com/OSC/ood-fileeditor/commit/5289a34a09ce3046765c654a50c098a4aeee605d

**Comment by brianmcmichael** [comment]
Keeping the `.env.production` staged, but updated it to be more generalized at https://github.com/OSC/ood-fileeditor/commit/b34c496b2a07ea24aaa02fa6e91e2a01721633f8
