### ISSUE TITLE
Add a .env.production that is compatible with the AweSim dashboard builder.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-fileeditor#38]
.env.production is pretty minimal here but the app fails to build on the new dashboard without the `OOD_DATAROOT` envvar.

Either the dashboard should be updated to not require this or I can just add OOD_DATAROOT to the .env.production here, even though there is no database in this app.

**Comment by ericfranz** [comment]
Not relevant since converting to Sinatra app, we are no longer using ood_appkit.
