### ISSUE TITLE
The .gitignore has some strange artifacts

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-fileeditor#40]
The `.gitignore` has some odd artifacts in there that need to be removed:

```
...

RAILS_DATAROOT=$PWD/data
RAILS_DATABASE=db/development.sqlite3

...
```

**Comment by brianmcmichael** [comment]
Interesting, it looks like those were put there by the old app template.

I'll remove them and make sure they're not still part of the RAT.

**Comment by brianmcmichael** [comment]
Done at f1d681fe49204ac5165d5b25406f72a8c04d6dc1
