### ISSUE TITLE
Upgrade to Rails 4.2 to fix warning during install

### ISSUE THREAD

**Issue by basilgohar** [OSC/ood-fileeditor#41]
During installation of ood-fileeditor, this warning kept getting issued:
`/root/ood/file-editor/vendor/bundle/ruby/gems/activesupport-4.0.0/lib/active_support/values/time_zone.rb:282: warning: circular argument reference - now`

**Comment by brianmcmichael** [comment]
Updating to Rails 4.2 should fix this.

**Comment by brianmcmichael** [comment]
Done at https://github.com/OSC/ood-fileeditor/pull/42

**Comment by ericfranz** [comment]
This commit 4e781b622527140d948c5fd1768d571ba40f7645 actually should be redone so that when upgrading to Rails 4.0.13 and then 4.1 and then Rails 4.2 the `bin/rake rails:update` task is run so that any file modifications are addressed.

**Comment by ericfranz** [comment]
References:

1. http://guides.rubyonrails.org/upgrading_ruby_on_rails.html
2. http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-0-to-rails-4-1
3. http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-1-to-rails-4-2

**Comment by brianmcmichael** [comment]
I've already done this process on other apps. There are no modifications to views that affect our apps, and following the official processes overwrites our own configurations.

**Comment by brianmcmichael** [comment]
There are some changes to the way Rails handles calling it's ActionX models, but rails itself is backward compatible to our code.

**Comment by ericfranz** [comment]
> following the official processes overwrites our own configurations

I think if you say yes to all of the files it wants to overwrite, then yeah. But on most of the files that you do a diff, there are things we changed and those changes can be sanely merged by manually adding them - or writing them over, then manually adding back the code that wasn't supposed to be changed. Its a matter of going through each suggested change and understanding it, and then deciding what to add and what to ignore. I'll post an alternative pull request and we can discuss next week after vacation.

**Comment by ericfranz** [comment]
Alternative to discuss: https://github.com/OSC/ood-fileeditor/pull/43

**Comment by brianmcmichael** [comment]
Closed by #43
