### ISSUE TITLE
Syntax highlighting should be enabled automatically for certain file types

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-fileeditor#53]
When opening a file, the editor starts in plain text mode. It would be nice when opening a file to auto-detect the type of file and set the appropriate syntax highlighting.

**Comment by brianmcmichael** [comment]
It looks like Ace provides an extension (Modelist) to help with this. It actually shouldn't be difficult to implement.

Ref:

https://github.com/ajaxorg/ace/blob/master/demo/modelist.html

http://ourcodeworld.com/articles/read/310/how-to-set-ace-editor-mode-according-to-the-file-extension-of-a-file
