### ISSUE TITLE
Attempting to edit an xml file produced a warning

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-fileeditor#55]
I tried to open an xml file for edit and saw this:

>The file you are attempting to edit is not in plain text format.
> application/xml

Reproduced in version v1.2.2 of file editor.

![screen shot 2017-03-09 at 1 47 17 pm](https://cloud.githubusercontent.com/assets/512333/23765415/26e3b65a-04cf-11e7-8787-7d499c9d8669.png)

**Comment by brianmcmichael** [comment]
`mime-type` isn't matching our regex for xml

https://github.com/OSC/ood-fileeditor/blob/master/app/controllers/pages_controller.rb#L9-L10

```
 2017-03-09 14:17:05 ⌚  oakley01 in ~/ondemand/dev/ood-fileeditor
± |master {2} ✓| → file -b --mime-type /users/PZS0562/efranz/dev/rss/motd_rss_example.xml
application/xml

 2017-03-09 14:17:15 ⌚  oakley01 in ~/ondemand/dev/ood-fileeditor
± |master {2} ✓| → file -b /users/PZS0562/efranz/dev/rss/motd_rss_example.xml
XML 1.0 document text
```


2 solutions:

1.) Enhance the regex: `text\/|application\/x-empty|\/xml`

 * we would probably have to add additional mime-types as well.

2.) **SIMPLER** Don't use `--mime-type` and match on regex `/text|empty/`

Which should match against these:
```
 2017-03-09 14:22:42 ⌚  oakley01 in ~/ondemand/dev/ood-fileeditor
± |master {2} ✓| → file -b manifest.yml
ASCII text

 2017-03-09 14:22:49 ⌚  oakley01 in ~/ondemand/dev/ood-fileeditor
± |master {2} ✓| → file -b README.md
ASCII English text, with very long lines

 2017-03-09 14:23:36 ⌚  oakley01 in ~/ondemand/dev/ood-fileeditor
± |master {2} ?:1 ✗| → file -b /users/PZS0562/efranz/dev/rss/motd_rss_example.xml
XML 1.0 document text

 2017-03-09 14:23:11 ⌚  oakley01 in ~/ondemand/dev/ood-fileeditor
± |master {2} ?:1 ✗| → file -b empty
empty

 2017-03-09 14:27:02 ⌚  oakley01 in ~/ondemand/dev/ood-fileeditor/bin
± |master {2} ?:1 ✗| → file -b rake
a /usr/bin/env ruby script text executable
```

but not against a real binary:

```
 2017-03-09 14:28:54 ⌚  oakley01 in ~/Apps/sublime_text_3
○ → file -b sublime_text
ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, stripped
```

**Comment by brianmcmichael** [comment]
Additional file types that wouldn't be matched in option 2.

```
 2017-03-09 14:32:37 ⌚  oakley01 in ~
○ → file -b v-dtrubyom-v-01.avi
RIFF (little-endian) data, AVI, 800 x 600, ~15 fps, video: XviD, audio: MPEG-1 Layer 3 (mono, 44100 Hz)

 2017-03-09 14:32:45 ⌚  oakley01 in ~
○ → file -b WP_20150824_003.jpg
JPEG image data, EXIF standard
```

**Comment by ericfranz** [comment]
Currently all the code is in the controller:

```ruby
  def index
    path = params[:path] || "/"
    path = "/" + path unless path.start_with?("/")

    @pathname = Pathname.new(path)
    if @pathname.file? && @pathname.readable?
      fileinfo = %x[ file -b --mime-type #{@pathname.to_s.shellescape} ]
      if fileinfo =~ /text\/|application\/x-empty/ || params.has_key?(:force)
        @editor_content = ""
        @file_api_url = OodAppkit.files.api(path: @pathname).to_s
      else
        @invalid_file_type = fileinfo
        render status: 404
      end
    elsif @pathname.directory?
      @directory_content = Dir.glob(@pathname + "*").sort
      @file_edit_url = Pathname.new(ENV['RAILS_RELATIVE_URL_ROOT']).join('edit')
    else
      @not_found = true
      render status: 404
    end

  end
```

1. We should think of a way we can move this into a model object that we can easily write tests against.
2. We should write those tests, including tests to verify that specific files produce a "warning" and others do not
3. We should then fix the code to not have the warnings

This would help as well with eventually integrating this app (if we choose to) with the dashboard.

**Comment by brianmcmichael** [comment]
See PR #55 for a bug fix. 

I think a full refactor with test coverage is a separate issue from fixing the bug.

**Comment by brianmcmichael** [comment]
#55 is not a good solution. 

Instead, the [ruby-mime-types](https://github.com/mime-types/ruby-mime-types)  Gem looks like a promising option, note particularly the API options for ascii and binary:

```
puts text.binary?               # => false
puts text.ascii?                # => true
```

**Comment by brianmcmichael** [comment]
`ruby-mime-types` won't work for this either.

```
irb(main):004:0> text.first
=> #<MIME::Type: application/xml>
irb(main):005:0> text.first.ascii?
=> false
```

**Comment by brianmcmichael** [comment]
According to this SO response, the only real exception to the text rule is XML, so the existing solution, with an additional accomodation for XML may be all we need.

http://stackoverflow.com/a/567787
