### ISSUE TITLE
Move public/ace-src-min-noconflict to vendor/assets and add to application.js manifest (or a separate manifest)

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-fileeditor#58]
Might require adding a non-minified ace version (but no conflict is good). This will let us ensure that the ace assets are cache busted and we can update to the latest version (which we probably haven't updated in a while).

**Comment by brianmcmichael** [comment]
Is minified still ok if possible? It cuts the dependency download size on the client side in half. We could track the current version in the folder name ex: `ace-src-min-noconflict-v1.2.6`

**Comment by ericfranz** [comment]
When building assets, sprockets will minify everything. So we would use the ace-src-noconflict and include it in the application manifest it will be minified appropriately.

**Comment by ericfranz** [comment]
Not relevant since converting to Sinatra app, we are no longer using Sprockets.
